# This file should not be used as is - instead should be used via Make which
# rewrites the below to match the current build environment.

version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ARG_DOCKERFILE
    image: ARG_IMAGE
    volumes:
      - ARG_PWD/.go:/go
      - ARG_PWD:/go/src/ARG_PKG
      - ARG_PWD/bin/ARG_ARCH:/go/bin
      - ARG_PWD/.go/std:/usr/local/go/pkg/linux_ARG_ARCH_static
      - ARG_PWD/.cache/go-build:/.cache/go-build
    working_dir: /go/src/ARG_PKG
    ports:
      - "8082:8082"
    command: /go/bin/ARG_BIN server --verbose
    depends_on:
      - postgres
    environment:
      - PGHOST=postgres
      - PGPASSWORD=password
      - PGUSER=policystore
      - POLICYSTORE_DATABASE_URL=postgres://policystore:password@postgres:5432/policystore_development?sslmode=disable
      - POLICYSTORE_ENCRYPTION_PASSWORD=topsecretpassword
      - POLICYSTORE_HASHID_SALT=Mm0W1jBfK3NUXcELUFEyIA==
      - POLICYSTORE_DASHBOARD_URL=http://dashboard.com

  postgres:
    build:
      context: ./docker/postgres
    ports:
      - "5432"
    volumes:
      - postgres_vol:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=policystore
      - POSTGRES_DB=postgres
      - DATABASES=policystore_development,policystore_test

volumes:
  postgres_vol:
